### ISSUE TITLE
Add ConnectionOptions to TransferOptions

### ISSUE THREAD

**Issue by jpdillingham** [jpdillingham/Soulseek.NET#186]
Presently, `ConnectionOptions` used for transfers are set at the client level, and there's no way to set them per transfer.

* [ ] Change the `TransferOptions` `ClientOptions` property to `DefaultTransferOptions`
* [ ] Add `ConnectionOptions` to `TransferOptions`
* [ ] Refactor a bunch of stuff to allow `ConnectionOptions` to be passed down and substituted wherever `ClientOptions.TransferConnectionOptions` is used today.

![image](https://user-images.githubusercontent.com/17145758/69245171-f5b66900-0b6b-11ea-9f3e-67eb5afa1b7f.png)

**Comment by screwfaze** [comment]
Any chance you have a beta available yet that I can test?

Thanks

**Comment by jpdillingham** [comment]
@screwfaze getting pretty close.  I'll probably have a Docker image with the example app ready to use by this time next week.

**Comment by screwfaze** [comment]
> @screwfaze getting pretty close. I'll probably have a Docker image with the example app ready to use by this time next week.

OMG I am really looking forward to that mate and thanks for making it docker coz that's how I run all my other apps. And thanks for all your hard work you are going to be a hero to all slsk users out there like me!!!

**Comment by jpdillingham** [comment]
After further consideration, adding `ConnectionOptions` to `TransferOptions` isn't worth the hassle.  `ConnectionOptions` contains only read and write buffer sizes and connect and inactivity timeouts, and the way indirect connections are established would require creating a registry of options to be applied when transfers are initiated.  

If someone can come up with a really compelling reason to add this we can reopen the discussion at that time.
