### ISSUE TITLE
Soulseek Browser

### ISSUE THREAD

**Issue by screwfaze** [jpdillingham/Soulseek.NET#2]
Hi,

Are you able to create a web interface for soulseek as there does not seem to be one. Would be amazing if soulseek could be controlled this way.

Thanks,

Alex

**Comment by jpdillingham** [comment]
Yes, this library is a necessary step to achieve that goal but I don't have an estimation of when it might be completed, or whether I'll fully carry through with it.

I'll keep this issue open and update it if/when work begins.

**Comment by screwfaze** [comment]
Thanks mate I hope this can get done someday really love slsk but so convenient nowadays to just use a browser from any device. Hope one day slsk will catch up with all the other p2ps out there.

**Comment by screwfaze** [comment]
Hi mate, can I try this yet do you have an installer or something just wanna play around and see how this looks. 

Thanks

**Comment by jpdillingham** [comment]
There's really nothing to look at; this is just a library.  If you want to see what is done so far you can install .NET Core 2.1 and run the console application in the `examples` folder; with this you can connect, log in, search for files, browse a user's files, and download a single file.

**Comment by jpdillingham** [comment]
A docker image containing the example app has been published; details are in the README.
