### ISSUE TITLE
vpn

### ISSUE THREAD

**Issue by screwfaze** [jpdillingham/Soulseek.NET#281]
Hi mate,

Hope you are well, I wanted to add a feature request when you have this up and running, is it possible to include a vpn with the soulseek docker for example like the one used by haugene/transmission-openvpn?

Thanks

**Comment by jpdillingham** [comment]
I can certainly take a look but I think that may go a bit beyond what I had planned for the example.  If someone else wanted to take this on I'd appreciate it.

**Comment by sharp004** [comment]
Maybe I would be easier to make a feature for redirecting the soulseek traffic through a proxy than adding a VPN to it ?
I mean there are a lot of docker containers which include a VPN and give the possibility to use it though Privoxy for example.

**Comment by jpdillingham** [comment]
This was moved over to slskd [here](https://github.com/slskd/slskd/issues/222) and ultimately closed.
