### ISSUE TITLE
How does this work without Soulseek (app) running? #Question

### ISSUE THREAD

**Issue by ldexterldesign** [jpdillingham/Soulseek.NET#306]
Hi,

Hope you're well

Thanks for software 🤯

I was under some assumption that this software piggybacks the Soulseek app in some way but to my delight I don't even need the Soulseek app running for this to work - what's going on here?

Keep up fantastic work!

Hope to hear back

Sincerely

**Comment by jpdillingham** [comment]
This is a from-scratch implementation of the Soulseek protocol; the only code that isn't new is the library I'm using for zlib compression (included [here](https://github.com/jpdillingham/Soulseek.NET/blob/master/src/Soulseek/Messaging/Compression/Zlib.cs) under the terms of the MIT license)

This was made possible by older projects having the foresight to document the protocol as they reverse engineered it, namely:

* Museek+: https://www.museek-plus.org/wiki/SoulseekProtocol
* SoleSeek: ftp://ftp.tu-clausthal.de/pub/mirror/ftp.gwdg.de/gnu/ftp/savannah/files/mldonkey/docs/Soulseek/soulseek_protocol.html

In addition I referenced a couple of open source projects to get more clarity on order of operations in a few cases:

* f-hj/slsk-client: https://github.com/f-hj/slsk-client
* misterhat/livelook: https://github.com/misterhat/livelook

Feel free to ask if you have any specific questions!

**Comment by ldexterldesign** [comment]
Bit fascinated about how one "reverse engineers a whole bloody protocol" but don't know where to start, short of reading [the wiki page] - any tips?

Sincerely

[the wiki page]: https://en.wikipedia.org/wiki/Communication_protocol

**Comment by ldexterldesign** [comment]
> SoleSeek: ftp://ftp.tu-clausthal.de/pub/mirror/ftp.gwdg.de/gnu/ftp/savannah/files/mldonkey/docs/Soulseek/soulseek_protocol.html

This is a good find

I'm thinking of it like HTTP and it's contenting my tiny brain... 🥴

Sincerely

**Comment by jpdillingham** [comment]
At the lowest levels it works the same as HTTP, just the data exchanged is different.  If you're interested in learning more you'd want to learn about TCP/IP and sockets.
