### ISSUE TITLE
Add docker restart policy #Enhancement #Idea #Suggestion

### ISSUE THREAD

**Issue by ldexterldesign** [jpdillingham/Soulseek.NET#310]
Hi!

Hope you're well

Thanks for bangin' software

Unsure why but my container always needs manually starting and I also suspect it stops by itself sometimes (I need to confirm this)

I suspect creating a [restart policy] will fix this

Perhaps this is a good time to offer a [compose] (too) - happy to attempt a PR as I've been looking for an excuse to consume the docker docs?

If you have any issues (e.g. questions/queries) then happy to help

Keep up great work!

Hope this helps and to hear back

Sincerely

[compose]: https://docs.docker.com/compose/
[restart policy]: https://docs.docker.com/config/containers/start-containers-automatically/
[run]: https://github.com/jpdillingham/Soulseek.NET#running-with-docker

**Comment by jpdillingham** [comment]
Thanks for pointing this out; I'm using `--restart always` on my local copy.  I'll update the docs and start script.
