### ISSUE TITLE
Search on mobile not working

### ISSUE THREAD

**Issue by screwfaze** [jpdillingham/Soulseek.NET#324]
Hi,

I cannot seem to search on my mobile phone using chrome browser the search button not showing up. Works fine on PC though.

Thanks

**Comment by jpdillingham** [comment]
I'll see what I can do.  I think the results are going to be pretty hard to read if they stack up like downloads, maybe I'll enable horizontal scrolling.

**Comment by screwfaze** [comment]
Thanks mate I am sure most people will want to do this on the go so that will be very helpful.

**Comment by jpdillingham** [comment]
I just pushed a new Docker image, take a look at let me know what you think.

**Comment by screwfaze** [comment]
Thanks mate working perfectly now on my mobile.
