### ISSUE TITLE
Feature Request - Strip folders

### ISSUE THREAD

**Issue by disguy2k** [jpdillingham/Soulseek.NET#339]
Please add the ability to not create subfolders, and just deposit the files in the download folder.

Thank you for creating a well thought out, low resource alternative to other containers out there. It's greatly appreciated.

**Comment by jpdillingham** [comment]
Thanks for the request.  I'm adding this to the next milestone (1.1.0) and it will likely get moved when I create the repo for the actual client, but I'll leave this open so I don't forget.

In the meantime I've added the `help wanted` label in case anyone wants to do it now.

**Comment by jpdillingham** [comment]
This is handled in slskd as of [0.13.0](https://github.com/slskd/slskd/releases/tag/0.13.0)
