### ISSUE TITLE
How to put Soulseek.NET behind a reverse proxy with nginx ?

### ISSUE THREAD

**Issue by sharp004** [jpdillingham/Soulseek.NET#364]
Hello,

First of all, thanks for the good work you're doing, and for the will to add soulseek in Lidarr !

I'm not very confortable with github, so I hope this is the good place for my question.
I'm looking for integrating your docker version of soulseek in OrganizrV2. To do that, I need a correct nginx conf but I tried many time with no success. Here is my nginx conf :

    location /soulseek {
        proxy_pass	http://soulseek:5000/;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    	}

I get this error in Google DevTool :
GET https://yyyyy.xxxxxx.fr/static/css/2.c19aca96.chunk.css net::ERR_ABORTED 404

Of course, docker soulseek is linked to docker Organizr with the "soulseek" alias, and is pingable from it.

Do you have a idea ?

Thanks in advance !

**Comment by jpdillingham** [comment]
Unfortunately the example application doesn't yet support this.  I've created issue #366 to track it and will begin work shortly, as this is something I always intended to add but hadn't gotten around to yet.

**Comment by sharp004** [comment]
Great, thank you !
