### ISSUE TITLE
Investigate transfer issues with Nicotine+

### ISSUE THREAD

**Issue by jpdillingham** [jpdillingham/Soulseek.NET#376]
The library has been tested extensively against Soulseek Qt and NS, but I haven't taken any time to test against other popular clients such as Nicotine+.

In initial testing, transfers both to and from Nicotine+ failed.  Investigate these to determine whether the incompatibility lies with this library or Nicotine+.

**Comment by jpdillingham** [comment]
When attempting to download from the example using Nicotine+:

```
 Failed to read a long integer (8 bytes) from position 80 of the message
```

**Comment by jpdillingham** [comment]
It doesn't appear as though Nicotine+ sends the file size in the transfer request.  I fixed this by checking the length and omitting the attempted read if no data is present, but now I'm getting `Cancelled` back from the transfer request acknowledgement.

**Comment by jpdillingham** [comment]
I can download from Nicotine+ to the example, but only one file at a time.  If I queue multiples I get connection errors.  This may be a timing issue.

**Comment by mathiascode** [comment]
Feel free to send any potential issues our way, and we'll look into them. :)

**Comment by jpdillingham** [comment]
@mathiascode thanks for chiming in; I was going to ping you when I had more information.

Turns out the issue was around [this](https://github.com/Nicotine-Plus/nicotine-plus/blob/master/pynicotine/transfers.py#L500) line, which has been recently changed.  The previous code was checking for a status of `Queued`, which is set from the text in the transfer response, and my code was sending `Queued.`, causing the condition to be unmet and cancelling the download.  I also added some logic for handling transfer requests with no size, which I think you may have addressed also (doesn't matter either way, I don't use it as it is unreliable).

There is an outstanding issue/question with connection handling, but I'll raise that over in your repo to continue the discussion.

**Comment by mathiascode** [comment]
The lack of a file size is likely because Nicotine+ only sends the file size with upload requests (see https://github.com/Nicotine-Plus/nicotine-plus/blob/master/doc/SLSKPROTOCOL.md#data-order-100).

I haven't checked what the official clients do nowadays, but I assume someone pulled this logic from previous documentation many, many years ago (ftp://ftp.tu-clausthal.de/pub/mirror/ftp.gwdg.de/gnu/ftp/savannah/files/mldonkey/docs/Soulseek/soulseek_protocol.prev.html).

**Comment by jpdillingham** [comment]
Reopened until more is understood about an issue with initially queued transfers: https://github.com/Nicotine-Plus/nicotine-plus/issues/653
