### ISSUE TITLE
Private messages always indicate that they are from an administrator

### ISSUE THREAD

**Issue by jpdillingham** [jpdillingham/Soulseek.NET#389]
This is probably a misinterpretation of the available documentation.

**Comment by mathiascode** [comment]
Seems like it was initially added here:
https://www.museek-plus.org/wiki/SoulseekProtocol?action=diff&version=56
https://github.com/eLvErDe/museek-plus/commit/7d9dfde7449b0d3ccb367a6384b575334f7c9e8f#diff-8d4024d76a46b6a9a58a212d4748d510R311

It's most likely a misinterpretation. I noticed that the value is false if the message was sent while you were offline, true if it's sent while you're online.

**Comment by jpdillingham** [comment]
Thanks for helping to clarify.  It works as you've suggested, and will also be set to false for messages that weren't acknowledged and are therefore replayed when you log in.  I've inverted the value and named the field `Replayed`; this made the most sense to me.
