### ISSUE TITLE
0 Search Results

### ISSUE THREAD

**Issue by Dirt-Nasty** [jpdillingham/Soulseek.NET#426]
Great work on this.  I wanted to get the container up and running in anticipation with Lidarr integration.

I'm having very sporadic results when doing searches - sorry if this is a dupe.

For example I did a search for "Lil Wayne" and I get back 0 results?

If I just search "Wayne" I do see results that I would have expected with the first string which leads me to believe something is a miss

Let me know what other things I can share to help debug

Thanks

**Comment by jpdillingham** [comment]
It appears as though this is one of the "banned" search phrases that are ignored by the server.  Try the same search using one of the official clients when in doubt; I tried this one and also got zero results using Soulseek QT.
