### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by kromsam** [jpdillingham/Soulseek.NET#478]
Hi there,

I (naively) tried to run the docker container on an `arm` architecture machine. Which resulted in:

`standard_init_linux.go:219: exec user process caused: exec format error`

An arm-based build would be great for all those RPi (and other SBCs) based home servers, like mine. As this projected is likely to be in some way or another implented in Lidarr in the future, arm-support would be vital! Are there any plans for this?

All the best, great work!

**Comment by jpdillingham** [comment]
Thanks for raising this.  The application can run on any platform .NET Core/5 can, I just need to find the right combination of base image and runtime configuration.  I'm publishing a bunch of binaries with [slskd](https://github.com/slskd/slskd/releases), but 32 bit ARM is not one of them.  I'll include that in the output artifacts so at least you can run outside of docker.

**Comment by jpdillingham** [comment]
Starting from the 0.9.5 release [here](https://github.com/slskd/slskd/releases/download/0.9.5/slskd-0.9.5-linux-arm.zip) `linux-arm` will be included in builds and releases.  I confirmed that this runs on a Raspberry PI 3, and should run on anything else with 32 bit ARM/7 architecture.

I've tried a couple of different base images for the docker image and haven't found one that will work yet.

**Comment by jpdillingham** [comment]
I'm going to need some time to think about the best way to approach this long term.  I've created an issue to track this in the slskd repo: https://github.com/slskd/slskd/issues/43, please keep an eye on it over there.
