### ISSUE TITLE
Add support for direct peer searches

### ISSUE THREAD

**Issue by jpdillingham** [jpdillingham/Soulseek.NET#499]
`SearchRequest` (code 8) is sent and received to/from an individual user in order to search just that user's shares.  This message class exists but is not referenced anywhere.

~~Modify `SearchAsync` to allow searches scoped to an individual~~
* [x] Handle and respond to incoming `SearchRequest` messages

**Comment by jpdillingham** [comment]
I think I added this message class anticipating adding support, but after observing the behavior of Soulseek Qt, it turns out that it sends message 42 (UserSearch) to the server instead of code 8 directly to the user, so this was just a gap that was never closed due to distraction.  The server forwards the request to the user, who has no idea they are being searched directly.

@mathiascode FYI

**Comment by mathiascode** [comment]
Thanks for the heads up! Seems like peer code 8 was the original message, which was later replaced with a server message. I'm guessing this change was made to allow filtering of blacklisted terms. Strangely, Nicotine+ uses the server message for buddy list searches, but not if you specify a username. I'll check the commit history to see what's up.

**Comment by mathiascode** [comment]
Peer code 8 was replaced in early 2006, see: https://github.com/Nicotine-Plus/nicotine-plus/blob/master/NEWS.md#version-120-may-10th-2006

Since neither SoulseekNS nor SoulseekQt support this peer message anymore, I'll replace its last usage in Nicotine+ and deprecate it in the documentation. My guess is that developers forgot to remove it completely once the official clients dropped support.

**Comment by mathiascode** [comment]
Slightly off-topic, but I wonder if server code 93 should go as well. I haven't personally seen this message in transit anymore, and I'd assume distributed code 93 replaced it at some point. For searches outside the distributed network (UserSearch, RoomSearch), the server always seems to send server code 26.

**Comment by mathiascode** [comment]
I'll spend some time trying to replicate code 93 distributed messages again, and analyze the traffic. Apparently "Direct Search Delivery" for privileged users should exist outside the distributed network, although I haven't seen such requests myself. https://www.slsknet.org/news/node/699

**Comment by jpdillingham** [comment]
Nice catch on this!  I'll make a donation and do some experimentation of my own.

If this is what code 93 is then I'm back to having absolutely no clue how to support a case where you become a branch root.  Maybe code 93 is used in both cases?

**Comment by jpdillingham** [comment]
I tried sending some user list and regular searches from a privileged account and neither results in a code 93 message.

**Comment by mathiascode** [comment]
Any difference in the traffic as a privileged user? If not, DSD has probably been decommissioned as well. My understanding is that the server should send FileSearch messages outside the distributed network to all online users, as long as the search originated from a privileged user. I could see this becoming an issue with many privileged users, so it could very well be discontinued.

**Comment by mathiascode** [comment]
I previously assumed distrib code 93 messages were sent from the server, but it seems like certain users send it. These users appear in the PossibleParents/NetInfo message at random, examples I found are DJSickers48 and *OmniMusic*. They send a BranchLevel message with value 0, and no BranchRoot message (connected directly to the server?).

**Comment by mathiascode** [comment]
Potentially useful for debugging:
Sending empty server code 81 and 82 messages to the server returns large responses (haven't decoded them yet). One of these messages is presumably known as "ChildParentMap" in SlskQt, probably server code 82, as the response contains usernames.

**Comment by jpdillingham** [comment]
> Any difference in the traffic as a privileged user?

Nope, I sent a server search for known files while the client wasn't connected to the distributed network and didn't receive anything.  I repeated the same search for the userlist and got `FileSearch`, same as when I had no privileges.  

The only time I have seen code 93 is directly from the server, and it was while I was working out how to respond to `NetInfo`.  My assumption at the time was that if you repeatedly fail to adopt a parent that the server would begin sending searches as code 93; it would stop sending `NetInfo` at the same time.  It wasn't random messages either, I was getting them at the rate you generally receive normal searches through the distributed network.  It has been a very long time since I have seen this, but I think I'll intentionally break `NetInfo` handling to see if I can reproduce it.

It doesn't seem like clients that have repeatedly failed to adopt a parent would make a good branch root, so I think my theory is probably incorrect.

I do recall seeing code 93 from a few different parents but I assumed that they were coming from a client that didn't properly implement the protocol; my code receives server code 93 and then broadcasts distributed code 3 to children.  Now that I think about it though, I'm not so sure this is someone unintentionally broadcasting, as the code size is different so it can't be a dumb forwarding mechanism.  I'm curious what client(s) this might be coming from, it can't be a long list.

**Comment by mathiascode** [comment]
> I'm curious what client(s) this might be coming from, it can't be a long list.
The few parents that sent code 93 messages all seemed to be using SoulseekQt when I checked.

**Comment by jpdillingham** [comment]
Reviewing my handling of code 93 dug up this: https://github.com/jpdillingham/Soulseek.NET/blob/master/src/Messaging/Messages/Distributed/DistributedServerSearchRequest.cs#L73-L74

```

            // nobody knows what this is.  always 0000000331000000 in hex.
            reader.ReadBytes(8);

            var username = reader.ReadString();
            var token = reader.ReadInteger();
            var query = reader.ReadString();

            return new DistributedServerSearchRequest(username, token, query);
```

I don't recall how I concluded that nobody knows what it is, I must have seen it referenced somewhere.

**Comment by mathiascode** [comment]
> I don't recall how I concluded that nobody knows what it is, I must have seen it referenced somewhere.

IIRC, no documentation about this existed prior to your findings.

> It doesn't seem like clients that have repeatedly failed to adopt a parent would make a good branch root, so I think my theory is probably incorrect.

Perhaps there are multiple conditions for receiving requests from the server, one being a last resort for failed connectivity, ultimately excluding the user from receiving children as well (https://github.com/jpdillingham/Soulseek.NET/issues/229#issuecomment-593136560), and another one for becoming a branch root, accepting children as usual?

**Comment by jpdillingham** [comment]
I'd get a lot more value out of all these little notes I have been leaving myself if I would go back and read them :)

Testing tonight and I can't get the server to stop sending me `NetInfo`, let alone begin sending code 93 searches.  I have tried:

* Sending `HaveNoParents: true` after each message
* Sending nothing after each message
* Sending `AcceptChildren: true` after login, in addition to the existing `HaveNoParents`
* Sending `HaveNoParents: false`, waiting 10 seconds, then sending `HaveNoParents: true`

I also tried sending `0.0.0.0` for `ParentsIP` instead of a blank string and that didn't have any effect either.

I'll have to pick through commits around the time I was working on this and see if I can figure out what I was doing to cause it.

**Comment by jpdillingham** [comment]
I'm still unable to get code 93 messages directly from the server, and I'm starting to question whether I may have been mistaken regarding the source.  I've connected to 3-4 different branch roots this morning and all of them are sending code 93.

I've been adding them to my list in Soulseek Qt and the thing common to all of them is their transfer speeds; they are all extremely high, in the 8k+ range.  It makes sense to me that the server would choose the fastest users as branch roots.

I noticed that Soulseek.NET doesn't seem to update the server with this information (#505) so I'll figure that out, then probably fake that information to see if I can get myself to act as a branch root.

**Comment by mathiascode** [comment]
> I've been adding them to my list in Soulseek Qt and the thing common to all of them is their transfer speeds; they are all extremely high, in the 8k+ range. It makes sense to me that the server would choose the fastest users as branch roots.

Good catch!

**Comment by mathiascode** [comment]
I investigated a bit. Seems like the NetInfo/PossibleParents message always contains users with a transfer speed higher than your own (becomes clear as the list length shrinks on higher speeds). Once you reach a transfer speed higher than every user online, NetInfo messages stop, and you're likely ready to become a branch root, although Nicotine+'s implementation seems too incomplete to initiate this.

**Comment by mathiascode** [comment]
Confirmed, the server just started sending code 93 messages.

**Comment by jpdillingham** [comment]
Great finds!  I'll have to figure out how to handle this officially.  It's clear now that my practice of forwarding server code 93 messages to my distributed message handler and then converting them to distributed code is incorrect.  I guess it must be ok to do this if you get a code 93 from a parent.

**Comment by mathiascode** [comment]
What's interesting is that the distributed code integer sent with the SearchRequest server message is `3` (https://github.com/Nicotine-Plus/nicotine-plus/blob/master/doc/SLSKPROTOCOL.md#data-order-49), so I'm still not sure why branch roots send code 93 instead of 3. Perhaps this value is ignored entirely.

**Comment by jpdillingham** [comment]
This morning I logged in with Soulseek NS using a user that has an artificially inflated speed, and I see in the diagnostics view:

```
m_serverIsParent = true
```

This user is, according to Soulseek.NET, promoted to branch root upon login.  I'm taking this as another confirmation that we've correctly interpreted the behavior in this thread.
