### ISSUE TITLE
Inform server of our file count and speed

### ISSUE THREAD

**Issue by jpdillingham** [jpdillingham/Soulseek.NET#505]
Other users, when viewed in Soulseek Qt from the user list, provide information about number of files shared and their overall transfer speed.  Soulseek.NET doesn't, and it isn't clear why.

Investigation is needed, but I suspect the server is expecting us to send this information at some point.

**Comment by mathiascode** [comment]
This would be the SharedFoldersAndFiles (code 35) and SendUploadSpeed (code 121) server messages. Nicotine+ sends the SendUploadSpeed message when an upload finishes, and the SharedFoldersAndFiles message when shared files have been rescanned.

**Comment by jpdillingham** [comment]
File and folder accounts appears to be implemented through `SetSharedCountsAsync()`, but apparently was never wired up.

Code [34](https://www.museek-plus.org/wiki/SoulseekProtocol#ServerCode34) is `SendSpeed`.  The Museek documentation says this is deprecated, and it appears to have been replaced by 121.

**Comment by mathiascode** [comment]
> The Museek documentation says this is deprecated, and it appears to have been replaced by 121.

Speaking of documentation, feel free to contribute to the protocol documentation at https://github.com/Nicotine-Plus/nicotine-plus/blob/master/doc/SLSKPROTOCOL.md if you find any incorrect information. It's a continuation of the original Museek/Nicotine documentation that I've attempted to keep up-to-date.

**Comment by mathiascode** [comment]
> File and folder counts appears to be implemented through `SetSharedCountsAsync()`, but apparently was never wired up.

Thought I'd mention that the server broadcasts the count to each user in a joined room, even in the count didn't change since the last sent message. Until a few days ago, Nicotine+ incorrectly sent this message to the server after each download finished, regardless if the downloaded file was auto-shared or not, resulting in useless traffic between the server and room users.

**Comment by jpdillingham** [comment]
Good to know, I'll suppress updates if nothing has changed.

**Comment by jpdillingham** [comment]
The server averages your reports and saves them when you log out.  I originally thought I'd have to send my previous speed on each login, but the thing to do here is just report the speed for each transfer as it finishes.

It crossed my mind to stash my average (or get it from the server upon login) and toss out any really high or low numbers, but I'll leave it up to the server to figure out what to do with these.
