### ISSUE TITLE
Add the ability to function as a distributed branch root

### ISSUE THREAD

**Issue by jpdillingham** [jpdillingham/Soulseek.NET#508]
Per discussion in #499, we now understand how the server chooses peers to act as a distributed branch root, and how and why distributed search requests are sometimes sent from the server directly (as code 93).

Review the logic in `ServerMessageHandler` and `DistributedConnectionManager` to ensure proper functioning when we become a branch root.  Things to consider/investigate:

* If the server decides that we should be a branch root, does it not send `NetInfo` (guessing no)? 
    * A: It depends.  If there are available parent candidates, the message will be sent.
* If our reported upload speed drops considerably, will the server "demote" us and stop sending code 93? 
  * If this happens, will it send `NetInfo` to let us know, or just stop sending searches?
    *  A: The server will only "demote" us from branch root and stop sending code 93 messages if we tell it that we have a parent (`HaveNoParents=false`).  If speed changes during the course of a session, the server will send an appropriate list of parent candidates.
* How exactly is the message with code 93 composed? What do the 8 bytes prior to the username represent?
  *  A: Still not 100% sure.  Code 93 is a "wrapper" around a distributed code 3 message.  The uncertainty is in knowing how the wrapper is composed, since only code 93 wrapping a code 3 message has been observed.

**Comment by mathiascode** [comment]
Just had a one-time occurrence after logging in, where the server sent a few code 93 search requests, stopped, and sent a NetInfo message.

**Comment by mathiascode** [comment]
It feels like the server is more likely to send you search results if you fail to connect to parents while your speed is high. On lower speeds, the server never sent me search requests, but now they seem to be rolling in fairly easily while the server also provides regular NetInfo messages. Investigation is needed with a more complete implementation than Nicotine+ currently provides.

**Comment by mathiascode** [comment]
Looking at previous patterns, it seems like the code 93 requests from the server started rolling in after the server provided an identical list of potential parents three times.

**Comment by jpdillingham** [comment]
I definitely need to do some testing, but for the first iteration I'm going to consider myself a branch root if I get a code 93 message from the server, and consider myself no longer a branch root if I receive a NetInfo message.

Based on your most recent comments, I don't have a lot of confidence in this approach but I'll see!

I haven't picked through old commits to confirm it, but I'm guessing I must have been sending a speed to the server at some point, otherwise I doubt I would have ever seen a code 93 message in the first place.

I'm also wondering if the mystery byte in the code 93 message might indicate whether we are or aren't a branch root.

**Comment by jpdillingham** [comment]
I'm pretty sure your observations so far are correct; the higher the speed I report, the fewer parent candidates I get in `NetInfo`.  I haven't yet pushed it far enough so that I'm the fastest client on the network but will confirm that as well.

The mystery bytes in the code 93 message are the same regardless of who sends it; `00-00-00-03-31-00-00-00`.

Logs from just now:

```
[22:13:09.059] [DIAGNOSTIC:DistributedConnectionManager] [Info] Attempting to establish a new parent connection from 5 candidates
[22:13:09.080] [DIAGNOSTIC:DistributedConnectionManager] [Warning] Failed to connect to any of the available parent candidates
[22:13:09.085] [DIAGNOSTIC:DistributedConnectionManager] [Info] Updated distributed status; HaveNoParents: True, ParentsIP: , BranchLevel: 0, BranchRoot: , ChildDepth: 0, AcceptChildren: False
[22:14:10.122] [DIAGNOSTIC:DistributedConnectionManager] [Info] Attempting to establish a new parent connection from 5 candidates
[22:14:10.123] [DIAGNOSTIC:DistributedConnectionManager] [Warning] Failed to connect to any of the available parent candidates
[22:14:10.124] [DIAGNOSTIC:DistributedConnectionManager] [Info] Updated distributed status; HaveNoParents: True, ParentsIP: , BranchLevel: 0, BranchRoot: , ChildDepth: 0, AcceptChildren: False
[22:15:11.210] [DIAGNOSTIC:DistributedConnectionManager] [Info] Attempting to establish a new parent connection from 5 candidates
[22:15:11.211] [DIAGNOSTIC:DistributedConnectionManager] [Warning] Failed to connect to any of the available parent candidates
[22:15:11.211] [DIAGNOSTIC:DistributedConnectionManager] [Info] Updated distributed status; HaveNoParents: True, ParentsIP: , BranchLevel: 0, BranchRoot: , ChildDepth: 0, AcceptChildren: False
[22:16:12.062] [DIAGNOSTIC:DistributedConnectionManager] [Info] Attempting to establish a new parent connection from 5 candidates
[22:16:12.063] [DIAGNOSTIC:DistributedConnectionManager] [Warning] Failed to connect to any of the available parent candidates
[22:16:12.064] [DIAGNOSTIC:DistributedConnectionManager] [Info] Updated distributed status; HaveNoParents: True, ParentsIP: , BranchLevel: 0, BranchRoot: , ChildDepth: 0, AcceptChildren: False
[22:17:13.171] [DIAGNOSTIC:DistributedConnectionManager] [Info] Attempting to establish a new parent connection from 5 candidates
[22:17:13.171] [DIAGNOSTIC:DistributedConnectionManager] [Warning] Failed to connect to any of the available parent candidates
[22:17:13.172] [DIAGNOSTIC:DistributedConnectionManager] [Info] Updated distributed status; HaveNoParents: True, ParentsIP: , BranchLevel: 0, BranchRoot: , ChildDepth: 0, AcceptChildren: False
[22:18:14.058] [DIAGNOSTIC:DistributedConnectionManager] [Info] Attempting to establish a new parent connection from 5 candidates
[22:18:14.059] [DIAGNOSTIC:DistributedConnectionManager] [Warning] Failed to connect to any of the available parent candidates
[22:18:14.060] [DIAGNOSTIC:DistributedConnectionManager] [Info] Updated distributed status; HaveNoParents: True, ParentsIP: , BranchLevel: 0, BranchRoot: , ChildDepth: 0, AcceptChildren: False
[22:18:37.558] [DIAGNOSTIC:DistributedConnectionManager] [Info] Promoted to distributed branch root.
```

It tries to connect for ~5 minutes, pauses for ~15 seconds, then sends the first code 93.  Same pattern twice in a row.

**Comment by jpdillingham** [comment]
With a crazy high speed > 100,000k/s the client connects, does nothing for between 5 and 10 minutes, then begins receiving code 93 from the server.  Next is to verify that children begin connecting.

**Comment by jpdillingham** [comment]
This morning I connected with a speed in the 300,000k range and after a 5-10 minute delay began receiving code 93 without having received `NetInfo`.  I left this connected for about an hour and a half with a timer requesting a list of parents and asking for children every 15 minutes, and no children ever attempted to connect.

**Comment by jpdillingham** [comment]
I've now also seen the case where I repeatedly fail to connect to the same list of parents and the server begins sending code 93.  It continues to send `NetInfo`.

I'm pretty confident that we understand the behavior now, as this all matches my original experience a year ago and again from the Nicotine+ observations.

I don't think we're really operating as a branch root under these conditions because child connections never come in.  With a high reported speed, and after connecting to a branch root, I gained 10 children within 2-3 minutes, so the network definitely prefers roots and other nodes closer to roots.

My theory right now is that the server is waiting for a specific message, or a value in an existing message (branch root, branch level, etc) as part of a "handshake" or acknowledgement from the client that it is ready to begin functioning as a root.

My plan now is to push my average speed back up to the point where no `NetInfo` is sent upon login, then log in with Soulseek Qt using the same account and see if I can figure out what's going on with Wireshark.

**Comment by jpdillingham** [comment]
I compared the data sent from client to server upon login with Soulseek.NET and Soulseek Qt and found that the only difference is that Qt sends a `AcceptChildren` message immediately upon receipt of the status of watched users.  This message, and apparently this message only (from a procedural perspective), determines whether children will attempt to connect.  After starting to send this message upon login I observed children connecting both before and after I had connected to a parent following a NetInfo, and before and after the server had begun sending code 93 without having sent a NetInfo, so the server doesn't appear to be the party responsible for deciding whether we have the info we need to effectively act as a branch root.

This matches logs in the 'DNet Server Messages' tab of Qt that I never understood until now:

```
[Thu Mar 25 09:23:24 2021] SM_SEND_DISTRIBUTIONS 1
[Thu Mar 25 09:23:24 2021] SM_DNET_GROUP_LEADER <your username>
[Thu Mar 25 09:23:24 2021] SM_DNET_LEVEL 0
```

Upon startup of the client, these three messages are added to the window.  `SM_SEND_DISTRIBUTIONS` I believe is equivalent to `AcceptChildren`.  This value is sent at login, but `SM_DNET_GROUP_LEADER` and `SM_DNET_LEVEL`, which I believe correspond to the `BranchRoot` and `BranchLevel` messages, are not (confirmed in Wireshark, and in testing the server doesn't care whether I send them or not).

The observation that the server only provides us with parent candidates if their speed exceeds our own was half true; the server doesn't provide us with parents that are _too much faster_ than us, either.  And the inverse is true.  With my speed nearing the maximum integer value, I received no `NetInfo` message and no children connected.  I rigged my code to report upload speeds that were 1/100th of the real speed and began downloading files from myself using another client.  Once my speed dropped to around 100k, children slowly began starting to connect.  I disconnected and reconnected several times, and each time the connections came in with roughly the same frequency.

Over the course of the day I downloaded more files to drop my average speed further, and as I did so child connections came in more frequently.  I reconnected several times and began to saw the list of parent candidates in `NetInfo` increase.

To summarize:

* The distributed network tries to pair parents and children that are within some unknown margin of speed.  Parents with speed above or below this margin will not be offered as candidates to children needing a parent.
* If the server can provide no parent candidates that match your speed (e.g. a NetInfo message would be empty), it will send code 93 search requests without ever sending `NetInfo` (unless perhaps your speed drops throughout your session, or a faster parent comes online)
* If the server has repeatedly provided a list of parent candidates and your client has not sent `HaveNoParents: false`, it will eventually begin sending code 93 search messages while continuing to send `NetInfo`.  How it determines when to start sending code 93 is unclear, but the higher your speed the more likely it will happen.  We know that the pool of available parents is smaller at higher speeds and this likely correlates.
* Sending `AcceptChildren`/code 100 with `1` will cause the server to consider you for inclusion in `NetInfo` messages sent to clients needing a parent.  I haven't confirmed that sending a `0` will remove you from consideration, but I'm pretty sure it would.
* The server appears to only consider the value of your last `AcceptChildren` message to determine your eligibility to appear in `NetInfo`; not whether you are connected to a distributed parent or if you are receiving code 93 messages, or if neither of those is true.

Given all of this, I think a reasonable implementation would be:

* Upon login, send `AcceptChildren 1` to begin receiving child connections (let them figure out whether you're a suitable parent; they should disconnect if you don't send any searches)
* If the client is not connected to a parent, consider branch level to be 0 and branch root to be the username of the logged in user, and send these values to any children that connect
* Accept all children that attempt to connect, regardless of other variables (subject to limits)
* If a `NetInfo` message is received, attempt to connect to each of the candidates.  If a parent is adopted, set branch level and root to the values provided by the parent, incrementing level by 1.
* If a code 3 distributed search is sent from a parent connection, broadcast it to children as is
* If a code 93 distributed search is sent from a parent connection, convert it to a code 3 search request and broadcast it to children
* If a code 93 distributed search is sent from the server, broadcast it to children as is (children are responsible for conversion to code 3)

It seems like setting `AcceptChildren` according to our ability to forward search requests would be a good idea, however Soulseek Qt doesn't appear to this, so we shouldn't worry about doing it either.  

The implementation above should leave us in a good state regardless of what the server chooses to do; if it stops sending code 93 directly when we connect to a parent, or starts after a parent disconnects, etc.  The only thing I'm not sure of is whether we would ever get code 93 search messages from the server, and also a parent.  If this is the case we'd duplicate searches sent to children.  I've seen this happen a few times (from a parent) and added some deduplication logic comparing only the previous request, so that might be a good thing to implement here too, keeping a small cache of the last 10 or so requests to solve for messages that may come out of order due to network lag.

**Comment by mathiascode** [comment]
Excellent, thanks for looking into this!

>     * Upon login, send `AcceptChildren 1` to begin receiving child connections (let them figure out whether you're a suitable parent; they should disconnect if you don't send any searches)

I haven't analyzed the network traffic, but it seems like child connection attempts only appeared once the first search requests started rolling in (according to the "Distributed Network" diagnostics tab in SlskQt).

**Comment by mathiascode** [comment]
Might be worth verifying what SlskQt does to its children once the parent changes/search requests stop coming in. I don't recall any situation where I've connected to a parent that didn't send any search requests (but it's possible I didn't pay attention).

**Comment by mathiascode** [comment]
What's also curious is that you're the only one of my child peers so far that have sent code 7 distributed messages...

**Comment by jpdillingham** [comment]
> I haven't analyzed the network traffic, but it seems like child connection attempts only appeared once the first search requests started rolling in

I'll take a closer look.  Having had some time to think about it, I'm thinking of toggling this based on whether I'm receiving searches.  It's not consistent with Qt but it makes more sense.

>  I don't recall any situation where I've connected to a parent that didn't send any search requests

It happens from time to time;  all of my peer sockets have a 15 second (by default) idle timeout that will close the connection if nothing is sent or received, and parents will sometimes disconnect due to this.  It might be better to send a ping to probe for connectivity instead, but it is highly, highly unlikely that there would ever be a natural 15 second lag between distributed searches so I'm not too concerned about it.  Although, without a good ping I can't be sure if the connection died or if the parent just stopped sending searches.

> you're the only one of my child peers so far that has sent code 7 (ChildDepth) distributed messages

I have been meaning to take that out.  The only time I have seen a child send any message whatsoever it was a ping and I'm 99% sure it was an early version of the example app from this repo sending it.

**Comment by mathiascode** [comment]
> It happens from time to time; all of my peer sockets have a 15 second (by default) idle timeout that will close the connection if nothing is sent or received, and parents will sometimes disconnect due to this. It might be better to send a ping to probe for connectivity instead, but it is highly, highly unlikely that there would ever be a natural 15 second lag between distributed searches so I'm not too concerned about it. Although, without a good ping I can't be sure if the connection died or if the parent just stopped sending searches.

I see, then there should be no issues. There's a 60 second timeout in Nicotine+ that must be handling this.

Has the 15 second timeout worked fine for you so far? I remember attempting to reduce the timeout at some point, which caused issues with extreme download speed limits (although this was probably closer to the 5 second range, way too strict in any case).

**Comment by jpdillingham** [comment]
The inactivity timeout is working so far, but I'm guessing that I'll need to tweak it down the road, specifically for transfers.  For message connections both clients will be pretty good about reconnecting when necessary. For browse responses I had to tweak the logic to reset the timer when data is received from the socket, not just complete messages.  This requires that the remote client starts sending data within 15 seconds which may be a problem with huge shares.  I'm pretty sure Qt will kill the connection prior to this anyway.

I do send ChildDepth but am planning to spend some time in Wireshark to see what Qt does.  I'm guessing that it is deprecated since children aren't using it anymore.

Regarding the distributed pings, I'm also going to test that by toggling search broadcasts with children connected to see if they ping me.  I know Qt pings the server if it hasn't heard anything in a while so this seems likely.

**Comment by jpdillingham** [comment]
I dissected the messages sent by Qt on login a bit closer and discovered a handful of messages that I previously missed.  After the login response is sent, the client sends a bunch of messages in one packet, and with a non-trivial number of users in your userlist it is easy to assume it is just one packet with those usernames. The breakdown is:

```
[<add user1/05>, <add user2/05>, ...]
<check privileges/92>
<set listen port/02>
<have no parents=1/71>
<branch root=username/127>
<branch level=0/126>
<shared files and folders/35>
[<get user1 status/36>, <get user2 status/36>, ...]
<accept children=1/100>
```

This definitely clears a few things up, and confirms a few old assumptions which I thought were untrue based on my previous findings.  It looks like the status is fetched for everyone on your userlist as well as anyone with which you have an open chat.

Watching the distributed tab of Qt it is clear that distributed children are actually pretty chatty, so I'm almost certain I have a bug preventing me from receiving messages from them.  I'm seeing lots of code 0/ping and 7/child depth, but not every child is sending them.

**Comment by mathiascode** [comment]
That makes more sense when considering the messages listed under the "DNet Server Messages" tab.

> Watching the distributed tab of Qt it is clear that distributed children are actually pretty chatty, so I'm almost certain I have a bug preventing me from receiving messages from them. I'm seeing lots of code 0/ping and 7/child depth, but not every child is sending them.

Could you check if they are using SoulseekQt or something else? Soulseek NS would likely send these messages, as the existing documentation is from that time period. When I ran SoulseekQt yesterday, none of my child peers sent any messages.

**Comment by mathiascode** [comment]
Another message that's seemingly nowhere to be found when analyzing SlskQt traffic is ParentIP (code 73), probably deprecated?

**Comment by mathiascode** [comment]
> I haven't analyzed the network traffic, but it seems like child connection attempts only appeared once the first search requests started rolling in (according to the "Distributed Network" diagnostics tab in SlskQt). Maybe SlskQt is rejecting some attempts, not sure?

I just received a child peer before receiving any search requests, so this seems like a false positive.

**Comment by jpdillingham** [comment]
After receiving a list of parent candidates, it sends a packet with a `ConnectToPeer` request for each.  After adopting a parent it sends:

```
<branch level/126>
<branch root/127>
<have no parents=0/71>
```

When adding a child it updates the server with child depth/129, as expected.  I would have expected to see ParentIP/73 in the packet above, and since it isn't there I think it is safe to assume it is deprecated.

I have a handful of children sending pings and have browsed them all and confirmed that paths don't start with `@@`, which is the only way I know how to tell Qt/NS (let me know if you know of another).  I think it is safe to assume that distributed pings and `ChildDepth` coming from children are deprecated, so I'm not going to send them, but pings will need to be handled and responded to so these clients can connect to me.

I did find a small bug in distributed connection handling, but nothing that would have prevented me from getting messages from children.  The random-ness supports the idea that NS sends these but Qt doesn't.

I also did confirm that the server will advertise you as a parent to children as soon as you set `AcceptChildren=1`, so I'm not going to send that until I either have a parent or I've gotten the first request from the server.

**Comment by mathiascode** [comment]
> I have a handful of children sending pings and have browsed them all and confirmed that paths don't start with `@@`, which is the only way I know how to tell Qt/NS (let me know if you know of another).

Another method is to check the "Upload allowed" value of a UserInfoReply message, which is included in responses from Slsk NS, but not SlskQt (due to its new group permission system). (I just realized this variable is missing from the documentation, but you can see it here: https://github.com/Nicotine-Plus/nicotine-plus/blob/0d7e1c7e6d3d5e6b82b19301b8cde9b13824ab7f/pynicotine/slskmessages.py#L2280)

**Comment by jpdillingham** [comment]
I fudged some code to ignore `NetInfo` until after the server had sent a code 93 and confirmed (4 times) that the server will stop sending code 93 after we send `HaveNoParents=false`.  There's a little bit of a delay (~500ms or so observed), presumably to flush buffers, but the messages do stop.  

I think that might have been the last outstanding question.  Can you think of anything else?

**Comment by mathiascode** [comment]
> Can you think of anything else?

Not at the moment.

> I would have expected to see ParentIP/73 in the packet above, and since it isn't there I think it is safe to assume it is deprecated.

Seems to be the case. I checked what Soulseek NS does, and code 73 was included along the other server messages like branch level and root.

**Comment by mathiascode** [comment]
One thing I realized is that the `SearchRequest `name for server code 93 is incorrect. While its only purpose is to deliver search requests at present, it's known as `SM_DNET_MESSAGE` in SoulseekQt. Wireshark calls it `Embedded Message`.

This raises more confusion around the code 93 distributed message, but only Nir knows why that one exists...

**Comment by jpdillingham** [comment]
Nice find! (I wasn't aware Wireshark had a dissector for Soulseek 🤦‍♂️ )

I always had a hunch that it was used as some sort of forwarding mechanism, but the fact that branch roots send code 93 to children disagrees with that.  I'd also love to know what these unknown bytes in both messages are.
