### ISSUE TITLE
Increase default connection timeout, handle delayed search result retrieval

### ISSUE THREAD

**Issue by jpdillingham** [jpdillingham/Soulseek.NET#513]
Watching network traffic this morning, I'm seeing incoming indirect connections coming in much later than expected, in one case 3 minutes, the other 7 seconds.  This is likely client-side buffering when processing search results.

To start, raise the default timeout from 5 to 10 or 15 seconds.  I don't think this will have a negative impact when negotiating a connection, since logic has been added (I think?) everywhere to attempt both indirect and direct connections simultaneously and take the first established.  It will elongate async operations that don't return until either the operation has finished, or all connection negotiation has timed out, though.

Ideally, indirect connection solicitations that we have sent should "hang around" for much longer, however given the async nature of all of the things that try to establish a connection (sending search results, browsing, getting info), I don't think this should happen in all cases, probably just when sending search results.  Consider the implications of this, paying special attention to how implementing code would handle it and what kind of performance implications might be a factor (thread pool starvation? memory concerns with large result payloads?)

**Comment by bruuteuzius** [comment]
That is why I went back to the desktop with slsk :/ Would be great if downloads work again ;)

**Comment by jpdillingham** [comment]
@bruuteuzius can you elaborate on where you are seeing timeouts? (which operations, which client, etc)?

Timeouts are configurable in both slskd and the example app in this repo, so you can increase those yourself.  This issue is just to increase the defaults, and potentially to use a different timeout when delivering search results.

**Comment by bruuteuzius** [comment]
![afbeelding](https://user-images.githubusercontent.com/9092482/112339863-56096d80-8cc0-11eb-9441-a3c02ddde9ad.png)
with this error in the logs of the docker container : [15:45:04 ERR] HTTP POST /api/v0/transfers/downloads/<username> responded 500 in 5005.5401 ms

**Comment by jpdillingham** [comment]
Another good reason to increase the default, as I hit this myself from time to time.  It wasn't top of mind when I created this issue.

In the meantime you can override the default by specifying something greater than 5 seconds:

```
-e "SLSK_CONNECT_TIMEOUT=15000"
```

In slskd the variable is `SLSKD_SLSK_CONNECTION_TIMEOUT`

**Comment by bruuteuzius** [comment]
Thanx JP!
