### ISSUE TITLE
Send a unique version when logging in

### ISSUE THREAD

**Issue by jpdillingham** [jpdillingham/Soulseek.NET#516]
The login message currently mimics Soulseek NS 157.  Modify the `LoginRequest` message to send a unique version, probably 170 (Nicotine+ uses 160).  Masquerading as a different client isn't really fair to Nir, and might be influencing some server behavior (although I have no proof of this).

**Comment by jpdillingham** [comment]
According to wireshark Soulseek Qt 2020.3.12 is sending a minor version of 100, so I am too.

Through testing I established that sending a minor version of 0 will prevent the server from sending `NetInfo`.  I suspect this is not the only thing that breaks.

**Comment by mathiascode** [comment]
I remember seeing interesting behavior when messing around with version numbers last time. Version >=179 is (most likely) blacklisted from the distributed network, see https://github.com/eLvErDe/museek-plus/issues/5#issuecomment-718350141.

**Comment by mathiascode** [comment]
Thanks for the friendly discussions so far, by the way. It's nice to have someone to discuss the Soulseek protocol with, which is rather uncommon these days. Development of third-party clients was essentially non-existent for many years.

**Comment by jpdillingham** [comment]
Likewise, these conversations have been great for improving my understanding of things (as evidenced by the number of bugs I'm finding...)
