### ISSUE TITLE
Time Remaining and Average Speed calculations fail for Transfer with StartOffset

### ISSUE THREAD

**Issue by jackBonadies** [jpdillingham/Soulseek.NET#602]
When using the DownloadAsync method with a non zero StartOffset (the greater the StartOffset the more pronounced the error is) the calculations for time remaining and average speed explode.  The reason is that after initiating the file connection with a peer and telling them our desired starting offset, we call UpdateState(InProgress) and then UpdateProgress(startOffset) (SoulSeekClient.cs:2712) this sets the speed with "var currentSpeed = (bytesTransferred - lastProgressBytes) / (ts.Value.TotalMilliseconds / 1000d);" (TransferInternal.cs:188).  The Timer value will be very tiny (since it only gets started at SoulSeekClient.cs:2712) and the difference between bytesTransferred and lastProgressBytes will be equal to the StartOffset (even though it should really be 0 since nothing was transferred yet).

A suggested fix is to set the lastProgressBytes to the StartOffset.

**Comment by jpdillingham** [comment]
Thanks for raising this, I'll have a look in the next few days.
