### ISSUE TITLE
Advice on getting stable results

### ISSUE THREAD

**Issue by maurei** [jpdillingham/Soulseek.NET#622]
My goal is setting up a console application that works through a bunch of search terms and downloads the best possible match.  I've adjusted the example console application in this repository to download files concurrently using a solution with `SemaphoreSlim`, very similar to [this one here](https://stackoverflow.com/a/22493662/4441216). When running for a predefined set of tasks, I get a lot of timeouts that I don't get when I run them synchronously. 

Any advice on how to work through a list concurrently with stability?

[edit]

Experimenting more with running the tasks synchronously, I get a lot of unstable results too, although less frequent.
 So perhaps, more generally speaking: what to do when during a `DownloadAsync` method call I get:
- No exception but the transfer state is `Completed, TimedOut`.
- An exception ("The wait timed out after 5000 milliseconds")

I'm also experiencing instability with searches. Consider for example the query `whitesquare acid flashes`. In the official soulseek client, it _always_ gives an abundance of results. Using this library, however, sometimes the results are empty, and sometimes they are populated.

For reference, the snippet below reproduces this:

```c#

SoulseekClient client = new (new SoulseekClientOptions(
    minimumDiagnosticLevel: DiagnosticLevel.Info,
    peerConnectionOptions: new ConnectionOptions(connectTimeout: 30000, inactivityTimeout: 15000),
    transferConnectionOptions: new ConnectionOptions(connectTimeout: 30000, inactivityTimeout: 15000)
));

await client.ConnectAsync("username", "password");


var options = new SearchOptions(
    15000,
    filterResponses: true,
    minimumResponseFileCount: 1,
    removeSingleCharacterSearchTerms: true,
    fileFilter: (file) =>
    {
        bool isMp3 = Path.GetExtension(file.Filename) == ".mp3";
        bool is320 = file.BitRate >= 320;
        bool longEnough = file.Length * 1000 >= t 326000 // hardcoded the track duration lower bound for example
        return isMp3 && is320 && longEnough;
    });

var responses = await _client.SearchAsync(SearchQuery.FromText("whitesquare acid flashes", options: options);

```

Thanks for your help!

**Comment by jpdillingham** [comment]
It can be fairly common for downloads to fail for some peers, especially if you don't have port forwarding configured such that you can receive incoming connections.  If a call to `DownloadAsync()` throws a `TimeoutException`, you should retry it immediately.  It shouldn't be possible for the call to complete with a state containing `TimedOut` without throwing, if it does that's a bug that I'll need to take a look at (please share a reproduction if you can).

Downloads from a single user will be constrained on the remote end to one transfer at a time, so adding additional controls to limit concurrency isn't needed.  My recommendation is to use `EnqueueDownloadAsync()` to enqueue all of the files you want, and then track the resulting tasks for completion.  The web example in this repo, or [slskd](https://github.com/slskd/slskd/blob/master/src/slskd/Transfers/API/Controllers/TransfersController.cs#L117-L171) can provide some guidance.

If you want a robust solution for individual tracks I would suggest using a queue to store the username and filename, then use a loop to pull records from it and download them.

Regarding search stability, I would strongly recommend performing one search at a time given your use case.  I haven't experimented with concurrent searches, but they should be possible.  Searches can take a lot of resources to process, depending on how many results come back.

Search results will vary given the nature of the network, but also depending on whether you have configured port forwarding such that you can receive incoming connections.  For a search result to be sent from a remote client to you, either they need to have port forwarding configured, or you do.  If you don't, then your results will be limited to people that have forwarding set up.

Let me know if that helps!
