### ISSUE TITLE
Browse Request fails on Inbound Direct connections

### ISSUE THREAD

**Issue by jackBonadies** [jpdillingham/Soulseek.NET#623]
Hi JP,

Hope you are doing well.  I have been investigating a bug for the last few days and finally found the cause and fix for it.  The conditions of the bug are as follows:

User A with an open port makes a search for "X".
Users B who have search results matching "X" make a direct connection to User A (peer init) in order to send said results.
User A sees search results and immediately decides to send a browse request to User B
--BrowseInternalAsync > GetOrAddMessageConnectionAsync.  The connection is cached in MessageConnectionDictionary so we use it.  We write the BrowseRequest just fine, and the read the BrowseResponse message from the connection just fine too.  Rather then the method returning successfully as it typically does it throws.  The code is stalled waiting on the responseConnectionWait, until it throws with the 60second timeout (even if we got the BrowseResponse far sooner than the timeout.  We never set the Task Completion Source on the BrowseResponseConnection waitkey.  This is because, for a direct inbound connection (unlike the other 3 possible connection types), we do not have an event handler hooked up to MessageReceived.

This seems to be a clear bug.  The fix is to set the message received handler on the inbound direct connection like we do for the other three.  My proposed fix is here: https://github.com/jackBonadies/SeekerAndroid/commit/5ffb072628ee08c060a57701fa88d3c1fcdf5851

The failure to browse will always occur if (1) a direct inbound connection is made.  and (2) the browse request is sent fast enough such that said connection is still in cache and therefore reused.  So the bug is very reproducible.

Let me know if you need more info, want me to make a pull request, etc.  Looking forward to your response.

**Comment by jpdillingham** [comment]
Wow, nice catch!  I had noticed intermittent failures with this but was putting off looking into it.

A PR would be great!

**Comment by jackBonadies** [comment]
All set!

**Comment by jpdillingham** [comment]
Thanks again!

Closed by #624
