### ISSUE TITLE
Handling Socket Abnormal Disconnects

### ISSUE THREAD

**Issue by jackBonadies** [jpdillingham/Soulseek.NET#628]
Hi JP,

When the tcp connection to the server disconnects in the normal way (i.e. .Close(), turn off network, logout, etc.), the library behaves well, transitioning the connection to the disconnected state.

An issue that I have been running into lately is when the tcp connection to the server disconnects in an abnormal or ungraceful way.  This can happen fairly easily, for example, on Android - if the phone is idle for too long it goes into something called "Doze" mode which interrupts the network connection causing said condition.  Network Stream writes will return no problem (since they only block until the user buffer is copied to kernel and not until it is received by the remote endpoint), and the Network Stream read will simply block - no exceptions will be thrown.  As such it is tough for the client application to determine that there is an issue at all (to give an example, using SearchAsync will not throw, it will simply return 0 results in a way that is indistinguishable from if one legitimately searched an actual query that happened to return 0 results due to being too rare).

Detecting this condition is tough.  A read timeout is a poor method imo, since often we are not expecting data from the server, and as a result it will cause the connection to disconnect frequently.  A "ping" (for example a GetStatus or such, i.e. at the application level not icmp) to the server is okay.. but it seems too costly.  The best method I found is to set TCP Option Keep Alive (see .NET Socket.IOControl).  This seems to work quite well - if the connection gets into a bad state it will throw and the library will transition things to be properly disconnected.  I set these options on the TcpClient in the ConnectAsync method.

The point of this issue is just to bring it to your attention and ask if you had any thoughts.  Perhaps it would be a good idea to add this potential fix to the library (either as the default or as an option)?  Or perhaps there are too many potential downsides (the case is too rare, it is not the libraries responsibility, it causes too much network traffic, etc.)?  

Hope this makes sense.  Looking forward to hearing your thoughts.

Thanks,
Jack

**Comment by jpdillingham** [comment]
Thanks for bringing this up.  I've been dealing with a similar issue with distributed child connections, where if the connection gets into a bad state the code keeps sending data for about 15 minutes, pushing memory usage very high.  I added a write queue that puts a cap on the number of concurrent writes, but now I'm questioning whether there's an option I can set on the connection, as you suggest.

I'll do some experimenting and see.

**Comment by jpdillingham** [comment]
I'm also seeing that there are read and write timeout options, which default to 0 (no timeout) that I've neglected to set.  I'm surprised that there's no timeout, and I'm guessing that the lack of a write timeout is the source of some of the issues.

I'll implement the keepalive too, as it seems like a good idea and I can't think of any harm in this context.  It looks... not straightforward.

**Comment by jpdillingham** [comment]
In the meantime I'd recommend using a timer and `PingServerAsync()`.  This, combined with the new write timeout option should achieve what you want to do.

**Comment by jackBonadies** [comment]
Thanks for this!  Here are some additional thoughts / findings for what its worth.  

I agree that IOControl isn't a good cross platform solution.  Though it does happen to have a unix implementation on Xamarin.. not sure if it actually worked though since using PInvoke to call getsockopt from libc did not return the options I had set via IOControl.  Using PInvoke to setsockopt did return the same socket options using getsockopt.  If you did want a cross platform solution, PInvoke is probably the way to go.  That being said, even with the options set, I did not see keep alive packets being sent in wireshark :/ So something is clearly not right.

Nicotine does use tcp keep alive packets (10s idle).  QT does not seem to (or if it does the idle time is more than a few minutes - observations via wireshark).

A timer and PingServerAsync() would certainly solve the problem.  Write Timeout, though it would not hurt, my understanding is that since the write only actually waits when the send buffer is full and so it may take a very large number of writes (considering protocol messages are relatively small and buffer size is 1kb+) to actually realize no data is being sent.

**Comment by jpdillingham** [comment]
Thanks for additional context.

I played around a bit myself and found absolutely no impact from the `KeepAlive` or `WriteTimeout` options that were added.  

Write timeouts apparently only apply to synchronous writes, which I guess makes sense, but is disappointing.  I may write my own timeout logic similar to that in `ConnectAsync()` to shore this up.  Write timeouts are definitely a problem, and the double-buffered writes I added are working but are probably not the right approach.

The `KeepAlive` option either doesn't do anything, or, as I suspected, the default values are too high to make a difference.

I added a configuration delegate in #632 that should allow implementing code to do whatever it needs to configure the socket.  Using the example shown in the PR comments I was able to verify that keepalives are working:

![image](https://user-images.githubusercontent.com/17145758/143620867-bd981538-35f4-4e64-93c0-70c28f1e3e2b.png)

This approach will work on anything targeting .NET Core 3.1 or later.  I'm not that familiar with Xamarin, but if it is still using Mono then IOControl or PInvoke is probably your best bet, and should work just fine with the delegate.  I'd appreciate if you could try it out and let me know if it works.  Anyone targeting .NET Core < 3.1 or .NET Framework would be interested in your solution.

**Comment by jackBonadies** [comment]
Here is a solution for those not on .NET Core 3.1+.  I tested it on linux (debian, glibc).  This uses PInvoke and works on systems with libc.  This requires compiling the calling application with unsafe (not the library itself).  I think there is a way without "unsafe" by using structs, but I am not knowledgeable of PInvoke.

`     [DllImport("libc", SetLastError = true)]
        public static extern unsafe int setsockopt(int socket, int opt1, int opt2, void* name, uint size);

        public const int SOCKET_LEVEL = 1;
        public const int TCP_LEVEL = 6;
        public const int KEEP_ALIVE = 9;

        public const int KEEP_IDLE = 4;
        public const int KEEP_INTERVAL = 5;
        public const int KEEP_COUNT = 6;
        
        static async Task Main(string[] args)
        {
            SoulseekClientOptions options = new SoulseekClientOptions(serverConnectionOptions: new ConnectionOptions(
                configureSocketAction: (socket) =>
                {
                    unsafe
                    {
                        uint size = 4;
                        int on = 1; //1 = On
                        setsockopt((int) (socket.Handle), SOCKET_LEVEL, KEEP_ALIVE, &on, size);
                        int idle_time = 4; //seconds
                        setsockopt((int) (socket.Handle), TCP_LEVEL, KEEP_IDLE, &idle_time, size);
                        int interval = 4; //seconds
                        setsockopt((int) (socket.Handle), TCP_LEVEL, KEEP_INTERVAL, &interval, size);
                        int count = 3; //count
                        setsockopt((int) (socket.Handle), TCP_LEVEL, KEEP_COUNT, &count, size);
                    }
                }));
            SoulseekClient client = new SoulseekClient(options:options);`


![2021-11-26_17-46](https://user-images.githubusercontent.com/13188205/143659642-b2091a3a-1f94-4dd5-b3fc-f40ca41ea331.png)
