### ISSUE TITLE
Invalid ChildDepth message sent to the server?

### ISSUE THREAD

**Issue by mathiascode** [jpdillingham/Soulseek.NET#641]
While looking through old Soulseek changelogs, the following entry in https://www.slsknet.org/157.html caught my eye:

> yes yes y'all, i screwed up the child depth relay code. here's a great example of why you shouldn't program when you're stoned. feeling geeky? ok then. one thing that's done on the new distributed network that's wasn't done before is that for each client we are now keeping track of what we call: child depth. when the client doesn't have any children, its child depth is 0. if the client has any number of children, its child depth is 1. unless they have any children of their own in which case it would be 2. unless those children have their own children... you get the idea. what child depth signifies is the number of levels of children a client has "under them". that information lets us make fairly sure that the distributed network as a whole doesn't grow past a certain depth, and that in turn helps give faster search results and more of them since ultimately there is less chance of failure along the way. this kind of depth information is collected from the very bottom of the network -- from childless children to parentmost parents each hop is automatically counted as one level of depth. this is what our problem was: without the proper intervening logic we made the client consider the word of the most recently talkative child over any of those that preceded. this is no good if we're already recorded to have one child of say, level depth 3 (thus making our own - 4) but then are told of a child that has a child depth of 0 (which incorrectly records our new depth as 1 when our actual depth hasn't really changed. silly? yes, but that's being overworked for ya. and this is what test 4 is all about fixing.

As far as I can tell, Soulseek.NET currently sends the number of children instead of depth in this message.

Does SoulseekQt send `ChildDepth` (server code 129) messages to the server anymore? Since SoulseekQt child peers no longer send `ChildDepth` (distributed code 7) messages to the parent, I don't see how we would know the correct value anymore, and surely anything sent by Soulseek NS clients would be invalid today?

I would assume this is fully deprecated in favor of traversing the distributed tree instead, but could you verify what SoulseekQt does on your end? I haven't seen any ChildDepth server messages sent yet, but then again, I haven't seen any Soulseek NS child peers yet.

**Comment by jpdillingham** [comment]
Nice catch!

I can say definitively that I have seen this message because I was handling it at one point: 831f6463a987599cf7f0551f0534d9324c9ba474

I was able to get some children connected and can confirm that two using Qt (files prefixed with `@@`) send neither `ChildDepth` nor distributed pings, and two using NS (files prefixed with a drive letter) sent `ChildDepth` shortly after connecting and are sending pings on an interval.

It makes sense that this would be deprecated in favor of `BranchDepth`, although I've never been able to tell whether that does anything either.  I just add 1 to whatever the parent sends.

**Comment by mathiascode** [comment]
> I can say definitively that I have seen this message because I was handling it at one point: [831f646](https://github.com/jpdillingham/Soulseek.NET/commit/831f6463a987599cf7f0551f0534d9324c9ba474)
> 
> I was able to get some children connected and can confirm that two using Qt (files prefixed with `@@`) send neither `ChildDepth` nor distributed pings, and two using NS (files prefixed with a drive letter) sent `ChildDepth` shortly after connecting and are sending pings on an interval.

Soulseek NS definitely sends the distributed message to parents, but does SoulseekQt forward this information to the server anymore? I'm wondering if I should mark the server message as deprecated in the protocol docs as well.

> It makes sense that this would be deprecated in favor of `BranchDepth`, although I've never been able to tell whether that does anything either. I just add 1 to whatever the parent sends.

I can imagine there's some fancy interface on the server side to plot the whole network, but we wouldn't know of course...

**Comment by jpdillingham** [comment]
I just took a look in Wireshark and I didn't see where `ChildDepth` was sent.  On connect it checks whether all of the userlist users exists, then concludes the packet with `AcceptChildren`.  I'd expect it to send a child depth of 0 around there, but it is also possible that it wouldn't until a child connects.

I agree with your thought that it is deprecated; if children don't send their depth then we couldn't possibly know what to send to the server.

I've had as many as 100 children in the past and was sending that to the server as the depth.  If it worked the way it is described I can't see how the server would have continued to send me children.  I've never connected to a parent deeper than 4 or 5, even back when I wasn't sending a speed to the server.

I've also removed it from the code and have been connected for about an hour and am up to 8 children.

**Comment by jpdillingham** [comment]
This sheds a little light on code 130/`DistributedReset`, also.  I'm guessing that the server will send this to children if the tree gets too deep.  Previously I thought it would have been sent if your speed and the speed of your parent diverged too much, which might also be the case.

**Comment by mathiascode** [comment]
@jpdillingham By the way, have you been able to reach Nir in the past? Just wondering if there's any place where he still responds regularly, apart from the rare occasion in the forum.

**Comment by jpdillingham** [comment]
@mathiascode a while back I posted on the google group stating that I wanted to communicate a bug privately and he emailed me.  I explained the bug, and then haven't heard back.  I haven't checked to see if it's still a bug, but maybe I should.
