### ISSUE TITLE
Help Wanted ?

### ISSUE THREAD

**Issue by screwfaze** [jpdillingham/Soulseek.NET#65]
Hi JP.

I am a new beginner to Programming and would love to be involved in this project, Soulseek is a software that I have loved for many years and would like to assist in anyway I can to make it even better which is why I am offering my services to you for any tasks you might need someone to do and hopefully I can learn something from Master like you.

Thanks

**Comment by jpdillingham** [comment]
Not sure if you're still interested but I've created a couple of issues that would be good for a first timer.

**Comment by screwfaze** [comment]
Yeah sure mate I'm still interested.

**Comment by lempamo** [comment]
Apologies for necroing this PR, but I'm up for helping too. I can build up a desktop UI example with Avalonia UI, and maybe help with some other things as well

**Comment by jpdillingham** [comment]
That would be very helpful; I'm putting the final touches on the first
iteration of the library and it would be helpful to have another pair of
eyes on things to drive out any design issues or bugs.

**Comment by jpdillingham** [comment]
@lempamo I'd appreciate the help if you're still interested.

**Comment by lempamo** [comment]
yeah sure! still recovering from thanksgiving but sometime within the next few days ill submit a starting PR with my gui example (don't expect it to be fully complete though)

**Comment by jpdillingham** [comment]
Great, feel free to reach out if you need anything.  My goal is to get a pre-release out by the end of the year and the more feedback I can get on the public API the better.

**Comment by lempamo** [comment]
unfortunately, none of the .net core gui frameworks out there support all the features necessary for a desktop app. only way i can see a desktop app happening is by doing something like wrapping the 'Web' example in electron
