### ISSUE TITLE
Bug handling downloads from Soulseek Qt for files that no longer exist on disk

### ISSUE THREAD

**Issue by jpdillingham** [jpdillingham/Soulseek.NET#668]
Troubleshooting failed downloads from a user this morning, I stumbled upon some odd behavior that is definitely a bug, but that I also don't understand.

I've been able to reproduce the problem by removing a file from a share configured in Soulseek Qt and trying to download it.

The sequence appears to be:

* Enqueue the file successfully
* Soulseek Qt sends `UploadDenied`
* Soulseek.NET improperly handles `UploadDenied` somehow, and fails to abort the transfer

A bunch of odd stuff happens simultaneously after the connection attempt times out, and the logs suggest that a transfer connection _was_ established and seeked to the starting offset of the file.

I suspect that what is happening is that the remote client is sending a transfer response that indicates we are good to go, but then immediately fails because it can't open the file, sends `UploadDenied`, and then somehow doesn't clean up the transfer connection, or potentially doesn't cancel the connection or prevent Soulseek.NET from proceeding to establish it.

The first step is to get these transfers to explicitly fail when `UploadDenied` is sent, then see if this odd behavior still exists.

**Comment by jpdillingham** [comment]
```
[09:36:25.891] [DIAGNOSTIC:PeerConnectionManager] [Debug] Waiting for a direct or indirect transfer connection from <user> with remote token 38426 for @@zsmgd\slsk-shared\file.mp3

[09:36:25.900] [DIAGNOSTIC:PeerMessageHandler] [Debug] Upload of C:/slsk-shared/file.mp3 from <user> was denied: File read error.
```

Soulseek Qt is using the unmasked filename in the `UploadDenied` response, which obviously doesn't match the masked name that was requested and therefore the denial isn't properly correlated.  This is way less than ideal.

**Comment by jpdillingham** [comment]
@mathiascode I'm guessing this is a problem for Nicotine+ too because of this line: https://github.com/nicotine-plus/nicotine-plus/blob/master/pynicotine/transfers.py#L1202

**Comment by jpdillingham** [comment]
This is definitely a bug in Soulseek Qt.  The rest of the messages, including the very similar `UploadFailed`, all use the masked filename.

The odd behavior I'm seeing after `UploadDenied` is received is explained by the 'second chance' connection attempt added in #383; if the connection fails an outbound attempt is made, and it succeeds, but the transfer fails because the other end is not expecting it (or perhaps fails to read the file a second time).

Failure to await a connection in `AwaitTransferConnectionAsync` is the only clue that I have that an `UploadDenied` message has been sent.  I think the plan will then be to, before attempting this 'second chance' connection, check to see whether this user has sent an `UploadDenied` message that matches the filename (using some fuzzy logic), and if so, use that to fail the transfer definitively before attempting the outbound connection.

This has a fairly high likelihood of malfunctioning and I absolutely don't want to produce false positives and fail transfers that were not denied, so this fuzzy match is probably going to be limited to removal of the root of the path, normalizing path separators, and doing a case insensitive match.

For anything else that might fall through the gaps I'm going to have to add `UploadDenied` and `UploadFailed` events, so that calling code can at least report it to the end user.  Right now `UploadFailed` is handled but the diagnostic is at the debug level.

**Comment by mathiascode** [comment]
Yes, I've stumbled upon this before. Unfortunately there's a bug in SoulseekQt, but I haven't been able to successfully report it to Nir. I didn't feel like coming up with any clever workarounds for this, so the transfer will simply time out in Nicotine+, and be re-queued every three minutes like other failed transfers.

**Comment by mathiascode** [comment]
Is https://github.com/jpdillingham/Soulseek.NET/pull/383 still needed for recent Nicotine+ versions?

**Comment by jpdillingham** [comment]
I was wondering the same and have confirmed it; for whatever reason if I enqueue a bunch of files, Nicotine+ initiates the transfer connection for the first one but won't for any subsequent transfers.  I dropped a bunch of logs in https://github.com/nicotine-plus/nicotine-plus/issues/653 at the time and it looks like things are still working the same.

I know we established that I'm requesting that the transfer starts instead of enqueuing it, then requesting a start, and I'm guessing that has something to do with this behavior.

**Comment by jpdillingham** [comment]
The status in Nicotine+ changes to "Waiting for peer to connect", so I think this behavior is intentional and it must be something I'm doing that is hitting an edge case.  I'm also able to get two transfer so run concurrently.

**Comment by jpdillingham** [comment]
I think this behavior must be a side effect of the behavior described in #606 

I think my rationale still stands even knowing it may be causing this connection behavior.  On my end it delays the start of transfers by 10 seconds and that's pretty much the only negative impact (ability to detect `UploadDenied` notwithstanding)

**Comment by mathiascode** [comment]
> Waiting for peer to connect

I believe I removed that transfer status about a year ago. Could you try the latest development version at https://nicotine-plus.org/doc/TESTING.html#windows? There has been a large amount of code refactoring in the past year.

**Comment by jpdillingham** [comment]
That explains why I couldn't find it in the source.  With 3.2.1.rc1 the transfers are initiated in all cases and the backup/second chance logic isn't executing.

Unfortunately now I'm seeing transfers get stuck in 'Getting status' after I send `TransferRequest`, which is causing downloads to fail initially.  I can retry them after a minute or two and they start fine.  This looks a lot like the behavior I have been monitoring here: https://github.com/slskd/slskd/issues/318; that's actually what set me down this path this morning, I thought I had a reproduceable instance of it but it turned out to be the disk issue.  These transfers hang for 30-60 seconds consistently before proceeding and then failing to connect (Soulseek.NET gives up after waiting for a response 5 seconds).

I reverted to 3.2.0 and that seems to be working ok.  I see the blame on the line that assigns 'Getting status' is a month old, it's probably a recent regression.  3.2.0 solves the uninitiated transfer issue also.

**Comment by mathiascode** [comment]
Most likely a regression introduced in https://github.com/nicotine-plus/nicotine-plus/pull/1787. I'll investigate.

**Comment by mathiascode** [comment]
Do you have a log output from Nicotine+ when the issue happens? Right-click the log pane -> Log Categories -> enable "Messages", "Connections", "Transfers" debug logging.

**Comment by jpdillingham** [comment]
I'll grab some logs in the morning.

Regarding the `UploadDenied` issue I've decided that adding the events for denies and failures is enough; trying to coordinate around receipt of these messages and especially guess at masked vs unmasked filenames is likely to cause more issues than it solves.

**Comment by jpdillingham** [comment]
```
06:50:58 [Conn] Incoming connection
06:50:58 [Conn] Attempting direct connection of type P to user <username> ('<my public IP>', 50025)
06:50:58 [Conn] Received incoming direct connection of type P from user <username>
06:50:58 [Msg] <class 'pynicotine.slskmessages.ConnectToPeer'> {'token': 1, 'user': '<username>', 'conn_type': 'P', 'ip_address': '<my public IP>', 'port': 50025, 'privileged': 0}
06:50:58 [Msg] <class 'pynicotine.slskmessages.PeerInit'> {'sock': <socket.socket fd=7132, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.25', 2234), raddr=('192.168.1.1', 52416)>, 'addr': ('192.168.1.1', 52416), 'init_user': '<username>', 'target_user': '<username>', 'conn_type': 'P', 'token': 0}
06:50:58 [Msg] <class 'pynicotine.slskmessages.TransferRequest'> {'init': <pynicotine.slskmessages.PeerInit object at 0x000002115b401940>, 'direction': 0, 'token': 0, 'file': 'ratm\\Freedom\\03 - Wake Up.mp3', 'realfile': None, 'filesize': None}
06:50:58 [Transfer] Received download request 0 for file ratm\Freedom\03 - Wake Up.mp3 from user <username>
06:50:58 [Transfer] Checking if file is shared: ratm\Freedom\03 - Wake Up.mp3 with real path <path>\Freedom\03 - Wake Up.mp3
06:50:58 [Transfer] Legacy TransferRequest upload request: {'init': <pynicotine.slskmessages.PeerInit object at 0x000002115b401940>, 'direction': 0, 'token': 0, 'file': 'ratm\\Freedom\\03 - Wake Up.mp3', 'realfile': None, 'filesize': None} Response: <pynicotine.slskmessages.TransferResponse object at 0x00000211596b65e0>
06:50:58 [Transfer] Sending response to download request 0 for file ratm\Freedom\03 - Wake Up.mp3 from user <username>: 1
06:50:58 [Conn] Sending message of type <class 'pynicotine.slskmessages.TransferResponse'> to user <username>
06:50:58 [Conn] Found existing connection of type P for user <username>, using it.
06:51:00 [Conn] Cannot respond to indirect connection request from user <username>. Error: Timed out
06:51:00 [Conn] Removed connection of type P to user <username> ('<my public IP>', 50025)
06:51:28 [Transfer] Transfer ratm\Freedom\03 - Wake Up.mp3 with request 0 for user <username> timed out

(i click retry in the Nicotine+ UI)

06:51:36 [Transfer] Initializing upload request for file ratm\Freedom\03 - Wake Up.mp3 to user <username>
06:51:36 [Transfer] Requesting to upload file ratm\Freedom\03 - Wake Up.mp3 with transfer request 124 to user <username>
06:51:36 [Conn] Sending message of type <class 'pynicotine.slskmessages.TransferRequest'> to user <username>
06:51:36 [Conn] Found existing connection of type P for user <username>, using it.
06:52:07 [Transfer] Transfer ratm\Freedom\03 - Wake Up.mp3 with request 124 for user <username> timed out
06:52:36 [Conn] Removed connection of type P to user <username> ('192.168.1.1', 52416)
```

My guess is that the existing connection it grabs at 6:50:58 is the indirect one that never connected

**Comment by jpdillingham** [comment]
I grabbed the binary from a build just before the PR you referenced: https://github.com/nicotine-plus/nicotine-plus/actions/runs/1644689191

```
07:15:06 [Conn] Found existing connection of type P for user <user>, using it.
07:15:06 [Conn] Sending message of type <class 'pynicotine.slskmessages.TransferResponse'> to user <user>
```

The transfer connection opens immediately and everything works fine.

The binary from a build after it was merged has the bug: https://github.com/nicotine-plus/nicotine-plus/actions/runs/1646362976

I was able to reproduce the problem in Qt with great effort; it fails about 1/20th of the time, while Soulseek.NET is more like 19/20.  The logs differ, though:

```
07:49:29 [Conn] Incoming connection
07:49:29 [Conn] Attempting direct connection of type P to user <user> ('<public ip>', 64860)
07:49:29 [Conn] Received incoming direct connection of type P from user <user>
07:49:29 [Msg] <class 'pynicotine.slskmessages.ConnectToPeer'> {'token': 28, 'user': '<user>', 'conn_type': 'P', 'ip_address': '<public ip>', 'port': 64860, 'privileged': 0}
07:49:29 [Msg] <class 'pynicotine.slskmessages.PeerInit'> {'sock': <socket.socket fd=7076, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.25', 2234), raddr=('192.168.1.1', 50556)>, 'addr': ('192.168.1.1', 50556), 'init_user': '<user>', 'target_user': '<user>', 'conn_type': 'P', 'token': 0}
07:49:29 [Msg] <class 'pynicotine.slskmessages.QueueUpload'> {'init': <pynicotine.slskmessages.PeerInit object at 0x000001c38f383b80>, 'file': 'ratm\\Industry\\03 - Fistful Of Steel.mp3', 'legacy_client': False}
07:49:29 [Transfer] Checking if file is shared: ratm\Industry\03 - Fistful Of Steel.mp3 with real path <redacted>>\Industry\03 - Fistful Of Steel.mp3
07:49:29 [Transfer] Checked upload queue, attempting to upload file ratm\Industry\03 - Fistful Of Steel.mp3 to user <user>
07:49:29 [Transfer] Initializing upload request for file ratm\Industry\03 - Fistful Of Steel.mp3 to user <user>
07:49:29 [Transfer] Requesting to upload file ratm\Industry\03 - Fistful Of Steel.mp3 with transfer request 117 to user <user>
07:49:29 [Transfer] QueueUpload request: User <user>, {'init': <pynicotine.slskmessages.PeerInit object at 0x000001c38f383b80>, 'file': 'ratm\\Industry\\03 - Fistful Of Steel.mp3', 'legacy_client': False}
07:49:29 [Conn] Found existing connection of type P for user <user>, using it.
07:49:29 [Conn] Sending message of type <class 'pynicotine.slskmessages.TransferRequest'> to user <user>
07:49:29 [Conn] Established connection with user <user>. List of outgoing messages: []
07:49:29 [Conn] Removed connection of type P to user <user> ('<public ip>', 64860)
07:49:29 [Msg] <class 'pynicotine.slskmessages.ConnClose'> {'sock': <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>, 'conn_type': 'P'}
07:49:42 [Msg] <class 'pynicotine.slskmessages.PlaceInQueueRequest'> {'init': <pynicotine.slskmessages.PeerInit object at 0x000001c38f383b80>, 'file': 'ratm\\Industry\\03 - Fistful Of Steel.mp3', 'legacy_client': False}
07:49:51 [Msg] <class 'pynicotine.slskmessages.CheckDownloadQueue'> {}
07:49:59 [Msg] <class 'pynicotine.slskmessages.TransferTimeout'> {'transfer': <pynicotine.transfers.Transfer object at 0x000001c38e80a5f0>}
07:49:59 [Transfer] Transfer ratm\Industry\03 - Fistful Of Steel.mp3 with request 117 for user <user> timed out
07:50:42 [Conn] Removed connection of type P to user <user> ('192.168.1.1', 50556)
```

It's important to note that in order to break this reliably I have to wait for any/all established connections to disconnect first, so I think the root cause is a change in behavior in the logic that negotiates direct/indirect connections.  Soulseek NS didn't have any problems, and I wouldn't expect it to since it tries one type at a time.

Let me know if you want me to move all this info over to your repo.

**Comment by mathiascode** [comment]
I believe the direct connection's PeerInit message mistakenly removed when the indirect connection is closed/removed, since they share the same IP address key in a dict. I'll add a check to verify that the PeerInit message is correct before removing it.

https://github.com/nicotine-plus/nicotine-plus/commit/361a6154c07da90a0156112a86a048ad17f4fd82 (dev build will be ready in about 15 minutes)

If this doesn't fix the issue, you can open a bug report in the Nicotine+ repo.

**Comment by jpdillingham** [comment]
Same outcome unfortunately.  I'll create an issue this evening.

**Comment by mathiascode** [comment]
https://github.com/nicotine-plus/nicotine-plus/commit/f9a2dc277945f30483601a1f92ff3526ff11d00b should reject ConnectToPeer requests if a connection was already established, and fixes an issue where the 'P' connection type was used for 'F' connections if a PierceFireWall message arrived.

**Comment by jpdillingham** [comment]
The problem is fixed with this build: https://github.com/nicotine-plus/nicotine-plus/actions/runs/1694717247

Nice work!

**Comment by mathiascode** [comment]
I found another SoulseekQt quirk/bug, in case you're not handling it yet: https://github.com/nicotine-plus/nicotine-plus/commit/21630b483b5459e3d08e3ae7cc092d1fe9ddce5c

If a SoulseekQt client has uploaded a few files to a user, and decides to unshare their files with the user, the client will send an UploadDenied message for all finished uploads as well.

**Comment by jpdillingham** [comment]
Thanks for the heads up.  There's nothing I can do with either `UploadFailed` or `UploadDenied` in this library given the (mostly) stateless nature and timing, but it is helpful for slskd.

**Comment by mathiascode** [comment]
@jackBonadies tagging you in case this discussion is helpful for Seeker
