### ISSUE TITLE
Dispose Issues

### ISSUE THREAD

**Issue by jackBonadies** [jpdillingham/Soulseek.NET#703]
Hi JP,

This investigation of mine came about as the Dispose() method on SoulseekClient occasionally (though rarely) throws an exception.  

1. SoulseekClient.Dispose(bool) calls PeerConnectionManager.RemoveAndDisposeAll() and then PeerConnectionManager.Dispose().  I don't think this is causing any issues per say, but Dispose calls RemoveAndDisposeAll internally (wrapped in a Disposed check) so I think the call to PeerConnectionManager.RemoveAndDisposeAll() is redundant and should be removed.  DistributedConnectionManager doesn't have this same redundancy.  Waiter.CancelAll() is the same case, we call this inside Waiter.Dispose with the Disposed check and so it is redundant.

2. SoulseekClient Dispose can throw an unhandled exception.  This is due to DistributedConnectionManager.RemoveAndDisposeAll() which awaits the MessageConnections in ChildConnectionDictionary (I think PeerConnectionManager.RemoveAndDisposeAll() has the same issue but I have never seen it at runtime).  The majority of MessageConnections in ChildConnectionDictionary will be completed (since when a pending 'D' connection is made, we add a task returning MessageConnection to the dict then immediately await it. and if it fails we remove it), however, depending on timing it is possible that some of the Tasks we await inside RemoveAndDisposeAll will be in progress (after all, the server can give us a DNet child at any time).  These tasks will throw if the connection fails.  and unlike the initial connection establishment or BroadcastMessageAsync, we do not catch the exception.  We should add a catch clause with noop.  That way we can continue disposing of the other connections and especially the server connection.

Let me know if you want a PR fixing the issue and I would be happy to make it.  Thanks.

**Comment by jpdillingham** [comment]
Thanks for raising this!  A PR would be great, otherwise I'll take a look in a bit.

**Comment by jpdillingham** [comment]
Closed by #740

Thanks again!
