### ISSUE TITLE
Race Condition regarding login events

### ISSUE THREAD

**Issue by jackBonadies** [jpdillingham/Soulseek.NET#716]
Hi JP - There is a potential race condition where we log in (and so the server sets our status as online) but we have not yet set the told the server our listen port, and so when a peer asks the server for our address during this time the get peer address message has port of 0.  If said user does not have port open but we do, then there will be a cannot connect error, despite the fact that if the user had requested our address just a bit later, the connection would have worked out fine.

This sequence of events is not uncommon due to the fact that clients (Nicotine+, not sure about QT) will often re-request a failed download as soon as a user goes back online, making the timing between the log in message and the set listen port message quite sensitive.

My proposed solution is instead of waiting for the login response + the expected server messages of wishlist, parent ratio/speed to tell the server our listen port - to instead just send the set listen port message right after sending the login request message.  Since its only the set listen port message that is time sensitive perhaps it can be taken out of SendConfigurationMessagesAsync (which can remain in the same spot) and placed right after send login request.  If this sounds good I can test it further and make a pull request.

**Comment by mathiascode** [comment]
Although the official clients seem to send the `SetWaitPort` message after receiving a `Login` response from the server, it seems like Nicotine+ has been sending it right after sending the `Login` message for 20 years (dating back to the first version of PySoulSeek), FWIW.

https://github.com/nicotine-plus/nicotine-plus/blob/933e555218233f9cbe55157272b5dfa86cd76889/pynicotine/slskproto.py#L2182-L2199

**Comment by jpdillingham** [comment]
Thanks for reporting this!  I'm pretty surprised that timing is close enough to make a difference as it should just be a gap of a few milliseconds between the login request and when the listen port is set.  You might have an event handler bound somewhere that is delaying execution of `SendConfigurationMessages`?

I played around this morning and attempted to send `SetListenPort` prior to login, as this would be the only surefire way to avoid the problem, but unsurprisingly the server rejects the login afterwards.  I'm now combining both messages into the same byte array and sending them at the same time, which is the lowest latency way to send both.
