### ISSUE TITLE
automatic download of songs from a list

### ISSUE THREAD

**Issue by GonyRosenman** [jpdillingham/Soulseek.NET#727]
i'm not able to figure out if this is possible using this repo - 
i want to build a program that takes a list of song names, searches them on soulseek and downloads the first option. 

is it possible right now? 
is it possible to request a tutorial on that task?

(so far i manage to extract a list of song names from spotify using a package named spotipy)

**Comment by jpdillingham** [comment]
This is definitely possible but you'll have to do the work to perform the searches and select the downloads.

The [console example](https://github.com/jpdillingham/Soulseek.NET/tree/master/examples/Console) would be a good place to start.

**Comment by GonyRosenman** [comment]
could you please elaborate more?
i want to learn by myself of course but i need some help getting started. how do i run the console example? from the command line (i installed dotnet and managed to do a simple hello world example with dotnet)

should i start a new webapp project? or another type? 

many questions i know.. perhaps you can describe or point me to a tutorial for those unfamiliar with automations (but still not afraid to get hands dirty in code)

**Comment by jpdillingham** [comment]
You can run the example by cloning this repo, navigating into the Console example directory, and running:

```
dotnet run --project Console.csproj
```

The example contains a lot of the logic that you'd need, so you can borrow parts from that.  At a high level you will need to:

* Perform a search with the artist and track you are looking for:
  * ` var (search, responses) = await client.SearchAsync(SearchQuery.FromText(searchText))`
* Look through the list of `responses` returned by the call above to choose a username and a filename that you want to download
* Download that file:
  * `await client.DownloadAsync(<username>, <remote filename>, <local filename>)`

This would probably be easier using the API exposed by [slskd](https://github.com/slskd/slskd); you'd be able to use a language of your choosing.
