### ISSUE TITLE
Allow binding to a specific IP address

### ISSUE THREAD

**Issue by J-C-3** [jpdillingham/Soulseek.NET#780]
Soulseek.NET & slskd are great!

With my existing p2p solutions, I prefer to bind my client to ensure all my traffic is going out of my VPN connection instead of my local connection.

I think it would be great if Soulseek.NET would support binding to a specific IP instead of `0.0.0.0/0` .

I've taken some time today and made some minor modifications to both Soulseek.NET and slskd to support this. 

It needs some tests to be adjusted to support it, working through some bugs with live reloading of the config, and some refinement, but if this is of interest to others I would happily open a draft PR and continue.

I've never written in C# before, but if there's interest I'll happily continue onward and open a draft PR.

Thanks all!

**Comment by jpdillingham** [comment]
Thanks for the suggestion!

I think to get the desired effect, both the `Listener` and `Connection` classes need to be updated.  I'll put some thought into the best place to put this option.

If you have a branch I'd love to take a look!

**Comment by J-C-3** [comment]
Of course, here’s the commit:


https://github.com/J-C-3/Soulseek.NET/commit/5370e9a1b50a0ed402d9ade8a8265f74ff623d12

**Comment by jpdillingham** [comment]
Thanks, I'll take a look, but probably not for a week or so due to a personal backlog.

**Comment by J-C-3** [comment]
No rush at all! Just poking at it a bit for right now and it's not even close to a priority.

As I was poking at it a bit today I got the hot reload working, whether it should be done the way I do I'm not 100% sure at the moment.
There is an issue right now where if I change the IP alone live, I get an `Address already in use` exception.

I was attempting to allow the socket for the listener for address reuse, but was having difficulty accessing the `TcpListener.Server` through the Listener interface.  

 I squashed it down to the other commit:

https://github.com/J-C-3/Soulseek.NET/commit/d865965f9ffc8a06e8412e4e53c8cc2bcf7b16eb

**Comment by jpdillingham** [comment]
Completely forgot about this until I came in today to fix another issue!  I created a branch and cherry-picked your squashed commit, I'll do some testing and get this going probably next month when I'm off for the holidays.

**Comment by J-C-3** [comment]
Appreciate it, @jpdillingham ! 

No rush or anything! I appreciate all you’ve done on this project.

I’m no dot net dev or anything, so  I’m sure you’ll be able to implement it better than I did.

**Comment by jpdillingham** [comment]
@J-C-3 one last ping to close the loop! This capability was added to slskd in [0.19.2](https://github.com/slskd/slskd/releases/tag/0.19.2)

Thanks again for the suggestion and most of the implementation!

**Comment by J-C-3** [comment]
@jpdillingham appreciate the feature add! Thanks again for everything!
