### ISSUE TITLE
Can't search for term like 'x x x' one character with spaces

### ISSUE THREAD

**Issue by apkatsikas** [jpdillingham/Soulseek.NET#800]
Encountering this in slskd but it appears to be an issue in this .NET client.

![image](https://github.com/jpdillingham/Soulseek.NET/assets/24813300/6a0f5e07-a917-4413-b02e-05cfecd4b980)

slskd endpoint `/api/v0/searches` returns a 400.

"Search query must contain at least one non-exclusion term with length greater than 1 (Parameter 'query')"

https://github.com/jpdillingham/Soulseek.NET/blob/dbad108a2be2938989939e30783c4585545c4ec4/src/SoulseekClient.cs#L2133C17-L2133C17

I confirmed I can run this query in a client like Nicotine+

**Comment by jpdillingham** [comment]
Doing some digging I see that this is an [option](https://github.com/jpdillingham/Soulseek.NET/blob/master/src/Options/SearchOptions.cs#L54) that's on by default, and there's no way to change it in slskd.  I've created an issue over there: https://github.com/slskd/slskd/issues/1048
